### PR TITLE
Fix flaky csv url spec

### LINKED ISSUE #186: CSV link building fails on first CI attempt, not on rerun
We changed the CSV link building to happen by javascript recently. It has become a flakey test on CI.

It is either failing intermittently or only on the first attempt, I'm not really sure which. Every time I click on "Rerun jobs", it successfully passes the test. Github Actions doesn't have a way to link to failed tests that you have rerun.

My first guess is that the test isn't waiting long enough for the js to fire and the right link to appear.

### PR DESCRIPTION
**Pull request by ondrae**
Makes a flaky test assertion more precise and easier for the computers to handle. [Capybara](https://github.com/teamcapybara/capybara), which does our headless browser integration tests, does its best to interpret assertions of what it is looking for on a page. It will even wait a bit to give any js a change to work first. This small edit lets Capybara find the link fast.

I'm still not 100% on why it was flaky. I can reproduce it locally by adding a half second sleep before the assertion, getting it to fail every time. It makes no sense.

This flaky test has failed a few times on the deploy step, after passing when the tests first ran. I've clicked "Rerun job" which fixes it each time. I'm unable to link to a failure, because Github Action removes it when you manually rerun a job, yet you probably got emails about them failing.

Closes #186

### CODE REVIEW

File: spec/system/search_spec.rb [hunk 1]
```diff
@@ -270,7 +270,7 @@
     #  browse mode is bare link
     visit "/"
     find("#general-search-button").click
-    expect(page).to have_link href: "/search.csv"
+    expect(page).to have_link href: "search.csv?search=&starting_year=&ending_year="
```
Comment (folksgl) [inline spec/system/search_spec.rb:273]: If there is a transient failure here, it's unclear to me why it's occurring thus how this change resolves the issue. Does it resolve the issue, or is it making the issue less likely to occur?

**Review by folksgl — APPROVED** [review]
Personally I'm unsure how/why this is solving the issue

File: spec/system/search_spec.rb (hunk 1 above)
Comment (ondrae) [reply spec/system/search_spec.rb:273]: I think I've figured it out. When the page loads for the first time, the link with `href="/search.csv"` exists. When the search button is clicked in line 272, some js changes the csv link to match the current search (in this case an empty search).  The old line 273 would look for `href="/search.csv"` and it would sometimes find it, before the js would change the it. Most of the time it wouldn't though.

Capybara has an [implicit wait ](https://github.com/teamcapybara/capybara#asynchronous-javascript-ajax-and-friends) of two seconds, if it can't find what it is looking for at first. So it will wait for two seconds for the `href: "/search.csv"` to change to `href: "search.csv?search=&starting_year=&ending_year="`

The update line 273 matches what we want it to be after the js changes it. Capybara will consistently wait for it to change now.
